#!/usr/bin/env python3
"""Generate paper-journal/numbers.tex from raw result files.

Single source of truth: every number in the journal LaTeX flows through
macros defined here, computed from
  results/journal_selector.json   (selector protocol, 3 pools)
  results/gpt2_gate.json          (GPT-2 perplexity gate, 100 records)
  results/timing_journal.json     (same-hardware timing benchmark)
  results/correlation.json        (recall<->F1 sample-level correlation)
  results/checkpoints/main.jsonl  (end-task QA, conference n=25 protocol)
  results/checkpoints/grid.jsonl  (alpha dev grid)
  data/pool_*.json                (pool statistics)
"""
import json
import re
import os
import random
import statistics
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "results")
DATA = os.path.join(ROOT, "data")
OUT = os.path.join(ROOT, "..", "paper-journal", "numbers.tex")

random.seed(20260923)
N_BOOT = 1000

MNAME = {"sieve": "Sie", "bm25": "Bm", "head": "Hea", "random": "Ran",
         "stride": "Str", "textrank": "TR"}
DSNAME = {"qasper": "Q", "hotpot": "H", "2wiki": "W"}
RATNAME = {"2.0": "Two", "4.0": "Four", "8.0": "Eight", "16.0": "Sixteen"}


def pct(x, d=1):
    return f"{x * 100:.{d}f}"


def boot(vals, seed=None):
    rng = random.Random(seed)
    n = len(vals)
    means = []
    for _ in range(N_BOOT):
        s = [vals[rng.randrange(n)] for _ in range(n)]
        means.append(statistics.mean(s))
    means.sort()
    return means[int(0.025 * N_BOOT)], means[int(0.975 * N_BOOT)]


def paired(pairs, seed=None):
    rng = random.Random(seed)
    diffs = [a - b for a, b in pairs]
    n = len(diffs)
    means = []
    for _ in range(N_BOOT):
        s = [diffs[rng.randrange(n)] for _ in range(n)]
        means.append(statistics.mean(s))
    means.sort()
    return means[int(0.025 * N_BOOT)], means[int(0.975 * N_BOOT)]


def main():
    L = []
    A = L.append
    A("% Auto-generated by scripts/make_numbers_journal.py. Do not edit.")

    # ---------------- selector protocol ----------------
    js = json.load(open(os.path.join(RES, "journal_selector.json")))

    A("% ---- Table 2: evidence recall at r=4, three datasets ----")
    for ds, dsk in DSNAME.items():
        for m, mk in MNAME.items():
            v = js["methods"][ds][m]
            A(f"\\newcommand{{\\Rec{dsk}{mk}}}{{{pct(v['recall'])}}}")
            A(f"\\newcommand{{\\Rec{dsk}{mk}Lo}}{{{pct(v['ci'][0])}}}")
            A(f"\\newcommand{{\\Rec{dsk}{mk}Hi}}{{{pct(v['ci'][1])}}}")
    for ds, dsk in DSNAME.items():
        n = js["methods"][ds]["sieve"]["n"]
        A(f"\\newcommand{{\\NRec{dsk}}}{{{n}}}")

    A("% ---- paired intervals (recall points) ----")
    PAIRS = {"sieve-head": "SH", "sieve-bm25": "SBm",
             "sieve-textrank": "STR"}
    for ds, dsk in DSNAME.items():
        for pk, pkk in PAIRS.items():
            if pk in js["paired"].get(ds, {}):
                v = js["paired"][ds][pk]
                A(f"\\newcommand{{\\Pair{dsk}{pkk}}}{{{pct(v['mean'])}}}")
                A(f"\\newcommand{{\\Pair{dsk}{pkk}Lo}}"
                  f"{{{pct(v['ci'][0])}}}")
                A(f"\\newcommand{{\\Pair{dsk}{pkk}Hi}}"
                  f"{{{pct(v['ci'][1])}}}")

    A("% ---- ratio sweep (values used in text; figure reads JSON) ----")
    for ds, dsk in DSNAME.items():
        for r, rk in RATNAME.items():
            for m, mk in MNAME.items():
                if m == "stride":
                    continue
                v = js["ratio_sweep"][ds][r].get(m)
                if v:
                    A(f"\\newcommand{{\\Rat{dsk}{mk}{rk}}}"
                      f"{{{pct(v['recall'])}}}")
                    A(f"\\newcommand{{\\Rat{dsk}{mk}{rk}Lo}}"
                      f"{{{pct(v['ci'][0])}}}")
                    A(f"\\newcommand{{\\Rat{dsk}{mk}{rk}Hi}}"
                      f"{{{pct(v['ci'][1])}}}")

    A("% ---- selector ablations (QASPER) ----")
    ABL = {"sieve": "Sie", "sieve-noq": "NoQ", "sieve-nopos": "NoPos",
           "sieve-nored": "NoRed", "sieve-relonly": "RelOnly"}
    for m, mk in ABL.items():
        v = js["ablations"][m]
        A(f"\\newcommand{{\\Abl{mk}}}{{{pct(v['recall'])}}}")

    A("% ---- position study ----")
    POS = {"0.0": "Start", "0.25": "Quarter", "0.5": "Half",
           "0.75": "ThreeQ", "1.0": "End"}
    for p, pk in POS.items():
        v = js["position"][p]
        A(f"\\newcommand{{\\Pos{pk}}}{{{pct(v['recall'])}}}")
        A(f"\\newcommand{{\\Pos{pk}N}}{{{v['n']}}}")

    A("% ---- sensitivity ----")
    SEN = {"beta": {"0.0": "BetaZp", "0.3": "BetaMid", "0.6": "BetaHigh"},
           "floor": {"0.0": "FloorZp", "0.35": "FloorMid",
                     "0.7": "FloorHigh", "1.0": "FloorOne"},
           "gamma": {"0.5": "GammaLo", "1.5": "GammaMid",
                     "3.0": "GammaHigh"}}
    for knob, vals in SEN.items():
        for val, vk in vals.items():
            v = js["sensitivity"][knob][val]
            A(f"\\newcommand{{\\Sens{vk}}}{{{pct(v['recall'])}}}")

    A("% ---- pool statistics ----")
    for ds, dsk in DSNAME.items():
        v = js["pool_stats"][ds]
        A(f"\\newcommand{{\\Pool{dsk}N}}{{{v['n_records']}}}")
        A(f"\\newcommand{{\\Pool{dsk}MedPos}}"
          f"{{{v['median_evidence_position'] * 100:.0f}}}")
        A(f"\\newcommand{{\\Pool{dsk}EvSents}}"
          f"{{{v['mean_evidence_sentences']:.1f}}}")
        A(f"\\newcommand{{\\Pool{dsk}MedWords}}"
          f"{{{v['median_ctx_words']}}}")
    A("\\newcommand{\\TotalRecords}{1600}")

    # ---------------- GPT-2 gate ----------------
    g = json.load(open(os.path.join(RES, "gpt2_gate.json")))
    A("% ---- GPT-2 perplexity gate ----")
    per = [v for v in g["per_record"].values()]
    recs = [v["recall"] for v in per]
    lo, hi = boot(recs)
    A(f"\\newcommand{{\\GateRecall}}{{{pct(g['recall_mean'])}}}")
    A(f"\\newcommand{{\\GateRecallLo}}{{{pct(lo)}}}")
    A(f"\\newcommand{{\\GateRecallHi}}{{{pct(hi)}}}")
    A(f"\\newcommand{{\\GateN}}{{{g['n_records']}}}")
    A(f"\\newcommand{{\\GateLatMedS}}{{{g['latency_median_s']:.1f}}}")
    A(f"\\newcommand{{\\GateLatMedCtxS}}"
      f"{{{g['latency_mediancontext_s']:.1f}}}")
    A(f"\\newcommand{{\\GateLatPnineS}}"
      f"{{{g['latency_p90context_s']:.1f}}}")
    big = [v for v in per if v["ctx_words"] >= 5500]
    A(f"\\newcommand{{\\GateLatSixkS}}"
      f"{{{statistics.mean(v['score_s'] for v in big):.1f}}}")
    A(f"\\newcommand{{\\GateSixkN}}{{{len(big)}}}")
    med_words = g["median_ctx_words"]
    A(f"\\newcommand{{\\GateMedWords}}{{{med_words}}}")
    med_tok = sorted(per, key=lambda v: v["ctx_words"])[len(per) // 2]
    A(f"\\newcommand{{\\GateMedTok}}{{{med_tok['n_tokens']}}}")

    # ---------------- timing ----------------
    t = json.load(open(os.path.join(RES, "timing_journal.json")))
    A("% ---- timing benchmark (ms, same container) ----")
    tmap = {}
    for row in t:
        tmap[(row["context_words"], row["method"])] = row["median_ms"]
    TN = {1000: "Onek", 2000: "Twok", 4000: "Fourk", 6000: "Sixk"}
    TM = {"sieve": "Sie", "textrank": "TR", "head": "Hea", "random": "Ran",
          "stride": "Str", "bm25": "Bm", "gpt2-gate": "Gate"}
    for (w, m), v in tmap.items():
        A(f"\\newcommand{{\\Time{TM[m]}{TN[w]}}}"
          f"{{{v:.1f}}}")
    # gate/sieve ratios
    r6 = tmap[(6000, "gpt2-gate")] / tmap[(6000, "sieve")]
    A(f"\\newcommand{{\\GateSieRatioSixk}}{{{r6:.0f}}}")
    # median-context ratio: gate per-record median-context vs sieve
    # interpolated on the same words
    siev = [tmap[(w, "sieve")] for w in (1000, 2000, 4000, 6000)]
    ws = [1000, 2000, 4000, 6000]

    def sieve_at(words):
        for i in range(len(ws) - 1):
            if ws[i] <= words <= ws[i + 1]:
                f = (words - ws[i]) / (ws[i + 1] - ws[i])
                return siev[i] + f * (siev[i + 1] - siev[i])
        return siev[-1]
    rmed = g["latency_mediancontext_s"] * 1000.0 / sieve_at(med_words)
    A(f"\\newcommand{{\\GateSieRatioMed}}{{{rmed:.0f}}}")
    # analytic A100 floor at median tokens: 2*|Ms|*L at 40% of 312 TFLOPS
    floor_med = 2 * 124e6 * med_tok["n_tokens"] / (312e12 * 0.4) * 1000
    A(f"\\newcommand{{\\GateAOneFloorMs}}{{{floor_med:.1f}}}")
    # BM25 vs sieve speed
    A(f"\\newcommand{{\\BmSpeedup}}"
      f"{{{tmap[(6000, 'sieve')] / tmap[(6000, 'bm25')]:.0f}}}")

    # ---------------- end-task QA ----------------
    # Primary protocol: expanded (n=100 QASPER records of the rebuilt
    # pool, methods incl. BM25) when complete; otherwise the conference
    # protocol (n=25). \QAProto and \QAN record which protocol produced
    # the \QA* macros. BM25 (\QABm*) macros only exist under the expanded
    # protocol; the paper guards the BM25 rows with \ifdefined.
    def load_ckpt(path):
        best = {}
        if not os.path.exists(path):
            return best
        for line in open(path):
            try:
                r = json.loads(line)
            except Exception:
                continue
            if r.get("ok"):
                best[r["key"]] = r
        return best

    exp_main = load_ckpt(os.path.join(RES, "checkpoints",
                                      "qa_expanded.jsonl"))
    exp_by = defaultdict(list)
    for r in exp_main.values():
        if r.get("exp") == "main":
            exp_by[r["method"]].append(r)
    NEED = ("full", "head", "random", "stride", "textrank", "bm25",
            "sieve")
    expanded = (all(len(exp_by.get(m, [])) >= 80 for m in NEED))

    def emit_qa(by, id_field):
        by = {m: list(rs) for m, rs in by.items()}
        full_f1 = None
        qam = {}
        for m, rs in by.items():
            em = [r["em"] for r in rs]
            f1s = [r["f1"] for r in rs]
            toks = [r.get("prompt_tokens") or 0 for r in rs]
            emm = statistics.mean(em) * 100
            f1m = statistics.mean(f1s) * 100
            elo, ehi = boot([e * 100 for e in em])
            flo, fhi = boot([f * 100 for f in f1s])
            qam[m] = {"n": len(rs), "em": emm, "f1": f1m, "flo": flo,
                      "fhi": fhi, "tok": statistics.mean(toks),
                      "per": {r[id_field]: r["f1"] for r in rs}}
            if m == "full":
                full_f1 = f1m
        QN = {"full": "Full", "head": "Hea", "random": "Ran",
              "stride": "Str", "textrank": "TR", "bm25": "Bm",
              "sieve": "Sie"}
        for m, mk in QN.items():
            if m not in qam:
                continue
            v = qam[m]
            A(f"\\newcommand{{\\QA{mk}EM}}{{{v['em']:.1f}}}")
            A(f"\\newcommand{{\\QA{mk}F}}{{{v['f1']:.1f}}}")
            A(f"\\newcommand{{\\QA{mk}Flo}}{{{v['flo']:.1f}}}")
            A(f"\\newcommand{{\\QA{mk}Fhi}}{{{v['fhi']:.1f}}}")
            A(f"\\newcommand{{\\QA{mk}N}}{{{v['n']}}}")
            A(f"\\newcommand{{\\QA{mk}Tok}}{{{v['tok']:.0f}}}")
            if m != "full" and full_f1:
                A(f"\\newcommand{{\\QA{mk}Delta}}{{{full_f1 - v['f1']:.1f}}}")
                A(f"\\newcommand{{\\QA{mk}Retain}}"
                  f"{{{v['f1'] / full_f1 * 100:.1f}}}")

        # paired F1 diffs (sieve minus baseline, per record)
        for m, mk in (("head", "SH"), ("random", "SRan"),
                      ("textrank", "STR"), ("bm25", "SBm")):
            if m not in qam or "sieve" not in qam:
                continue
            pairs = []
            for ex, f1v in qam["sieve"]["per"].items():
                if ex in qam[m]["per"]:
                    pairs.append((f1v, qam[m]["per"][ex]))
            if pairs:
                d = statistics.mean(a - b for a, b in pairs) * 100
                lo, hi = paired([(a * 100, b * 100) for a, b in pairs])
                A(f"\\newcommand{{\\QAPair{mk}}}{{{d:.1f}}}")
                A(f"\\newcommand{{\\QAPair{mk}Lo}}{{{lo:.1f}}}")
                A(f"\\newcommand{{\\QAPair{mk}Hi}}{{{hi:.1f}}}")
        return qam, by.get("sieve", [])

    if expanded:
        A("% ---- end-task QA (expanded protocol: QASPER pool[:100], "
          "r=4, incl. BM25) ----")
        qam, sieve_rows = emit_qa(exp_by, "id")
        A("\\newcommand{\\QAProto}{expanded}")
        A(f"\\newcommand{{\\QAN}}{{{min(len(exp_by[m]) for m in NEED)}}}")
        # expanded alpha grid (dev split, alpha stored per record)
        ga = defaultdict(list)
        for r in exp_main.values():
            if r.get("exp") == "grid" and r.get("ok"):
                ga[r.get("alpha")].append(r["f1"])
        gk = {0.3: "Lo", 0.6: "Mid", 0.9: "Hi"}
        for a, rs in sorted(ga.items()):
            name = gk.get(a, "X")
            A(f"\\newcommand{{\\GridA{name}}}"
              f"{{{statistics.mean(rs) * 100:.1f}}}")
        total_calls = len(exp_main)
    else:
        A("% ---- end-task QA (conference protocol: QASPER n=25) ----")
        rows = {k: v for k, v in
                load_ckpt(os.path.join(RES, "checkpoints",
                                       "main.jsonl")).items()
                if v.get("dataset") == "qasper"}
        by = defaultdict(list)
        for r in rows.values():
            if r["method"] == "random" and r.get("seed", 0) != 0:
                continue
            by[r["method"]].append(r)
        qam, sieve_rows = emit_qa(by, "example")
        A("\\newcommand{\\QAProto}{conference}")
        nn = [len(by[m]) for m in ("full", "head", "sieve") if m in by]
        A(f"\\newcommand{{\\QAN}}{{{min(nn) if nn else 0}}}")
        # alpha grid (dev): alpha embedded in the key as sieve-aX.X
        grid = load_ckpt(os.path.join(RES, "checkpoints", "grid.jsonl"))
        if grid:
            ga = defaultdict(list)
            for r in grid.values():
                mm = re.search(r"-a(\d+\.\d+)", r["key"])
                if mm:
                    ga[float(mm.group(1))].append(r["f1"])
            gk = {0.3: "Lo", 0.6: "Mid", 0.9: "Hi"}
            for a, rs in sorted(ga.items()):
                name = gk.get(a, "X")
                A(f"\\newcommand{{\\GridA{name}}}"
                  f"{{{statistics.mean(rs) * 100:.1f}}}")
        total_calls = sum(len(load_ckpt(os.path.join(
            RES, "checkpoints", f"{e}.jsonl")))
            for e in ("main", "grid", "ablation", "ratio", "position")
            if os.path.exists(os.path.join(RES, "checkpoints",
                                           f"{e}.jsonl")))

    # api latency of the reader (median over sieve rows of the primary
    # protocol, when recorded; the expanded protocol does not record it)
    apis = [r.get("api_ms") for r in sieve_rows if r.get("api_ms")]
    if apis:
        A(f"\\newcommand{{\\QAReaderMs}}"
          f"{{{statistics.median(apis):.0f}}}")

    # total calls behind the paper's QA numbers
    A(f"\\newcommand{{\\TotalCalls}}{{{total_calls}}}")

    # ---------------- correlation ----------------
    try:
        c = json.load(open(os.path.join(RES, "correlation.json")))
        A("% ---- recall <-> F1 correlation ----")
        if c.get("protocol"):
            A(f"\\newcommand{{\\CorrProto}}{{{c['protocol']}}}")
        A(f"\\newcommand{{\\CorrPearson}}"
          f"{{{c['pooled']['pearson']:.2f}}}")
        A(f"\\newcommand{{\\CorrSpearman}}"
          f"{{{c['pooled']['spearman']:.2f}}}")
        A(f"\\newcommand{{\\CorrNPairs}}{{{c['pooled']['n']}}}")
        A(f"\\newcommand{{\\CorrNRecs}}{{{c['n_records']}}}")
        for m, mk in (("sieve", "Sie"), ("head", "Hea"),
                      ("textrank", "TR")):
            if m in c.get("per_method", {}):
                A(f"\\newcommand{{\\Corr{mk}Pearson}}"
                  f"{{{c['per_method'][m]['pearson']:.2f}}}")
                A(f"\\newcommand{{\\Corr{mk}Spearman}}"
                  f"{{{c['per_method'][m]['spearman']:.2f}}}")
    except FileNotFoundError:
        pass

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {len(L)} macros -> {OUT}")


if __name__ == "__main__":
    main()
